openapi: 3.0.1

info:
  title: Swagger Petstore
  description: SAMPLE
  version: 1.0.5

servers:
  - url: "https://example.com"

tags:
  - name: pet
    description: Everything about your Pets

paths:
  "/pet":
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetByIds
      parameters:
        - name: petIds
          in: query
          description: ID of pet to return
          required: true
          explode: false
          schema:
            type: array
            items:
              type: integer
              format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}

components:
  schemas:
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: doggie
        photoUrls:
          type: array
          items:
            type: string
